services:
  portainer:
    container_name: ${CONTAINER_NAME}
    image: portainer/portainer-ce:${IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${UI_AND_API_PORT}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINER_DIR}:/data
