services:
  homepage:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/gethomepage/homepage:${IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    volumes:
      - ${CONTAINER_DIR}/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
