services:
  uptime-kuma:
    container_name: ${CONTAINER_NAME}
    image: louislam/uptime-kuma:${IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${PORT}:3001
    volumes:
      - ${CONTAINER_DIR}:/app/data
